apiVersion: apps/v1
kind: Deployment
metadata:
  name: akb-app-deployment
  labels:
    app: akb-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: akb-app
  template:
    metadata:
      labels:
        app: akb-app
    spec:
      containers:
      - name: akb-app
        image: app-minikube:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: akb-app-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      #targetPort: 30066
      nodePort: 30069
  selector:
    app: akb-app
  type: NodePort